on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: docker/build-push-action@v2
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "localbuild/testimage:latest"


